// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {models} from '../models';

export function CreateProfile(arg1:string,arg2:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function GetActiveProfile():Promise<config.Profile>;

export function GetDefaultProfile():Promise<string>;

export function GetMusicFolder():Promise<string>;

export function GetPlaylists():Promise<Array<models.Playlist>>;

export function GetProfiles():Promise<Array<config.Profile>>;

export function Hello():Promise<string>;

export function RenameProfile(arg1:string,arg2:string):Promise<void>;

export function ScanAudioFiles(arg1:string):Promise<Array<models.AudioFile>>;

export function SelectFolder():Promise<string>;

export function SetDefaultProfile(arg1:string):Promise<void>;

export function SetMusicFolder(arg1:string):Promise<void>;

export function SwitchProfile(arg1:string):Promise<void>;

export function UpdateProfileMusicFolder(arg1:string,arg2:string):Promise<void>;
