// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetMusicFolder():Promise<string>;

export function GetPlaylists():Promise<Array<main.Playlist>>;

export function Hello():Promise<string>;

export function ScanAudioFiles(arg1:string):Promise<Array<main.AudioFile>>;

export function SelectFolder():Promise<string>;

export function SetMusicFolder(arg1:string):Promise<void>;
