// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Hello():Promise<string>;

export function ScanAudioFiles(arg1:string):Promise<Array<main.AudioFile>>;

export function SelectFolder():Promise<string>;
