// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Hello() {
  return window['go']['main']['App']['Hello']();
}

export function ScanAudioFiles(arg1) {
  return window['go']['main']['App']['ScanAudioFiles'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
