// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMusicFolder() {
  return window['go']['main']['App']['GetMusicFolder']();
}

export function GetPlaylists() {
  return window['go']['main']['App']['GetPlaylists']();
}

export function Hello() {
  return window['go']['main']['App']['Hello']();
}

export function ScanAudioFiles(arg1) {
  return window['go']['main']['App']['ScanAudioFiles'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetMusicFolder(arg1) {
  return window['go']['main']['App']['SetMusicFolder'](arg1);
}
