// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfile(arg1, arg2) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function GetActiveProfile() {
  return window['go']['main']['App']['GetActiveProfile']();
}

export function GetDefaultProfile() {
  return window['go']['main']['App']['GetDefaultProfile']();
}

export function GetMusicFolder() {
  return window['go']['main']['App']['GetMusicFolder']();
}

export function GetPlaylists() {
  return window['go']['main']['App']['GetPlaylists']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function Hello() {
  return window['go']['main']['App']['Hello']();
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function ScanAudioFiles(arg1) {
  return window['go']['main']['App']['ScanAudioFiles'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetDefaultProfile(arg1) {
  return window['go']['main']['App']['SetDefaultProfile'](arg1);
}

export function SetMusicFolder(arg1) {
  return window['go']['main']['App']['SetMusicFolder'](arg1);
}

export function SwitchProfile(arg1) {
  return window['go']['main']['App']['SwitchProfile'](arg1);
}

export function UpdateProfileMusicFolder(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfileMusicFolder'](arg1, arg2);
}
